# This is a basic workflow to help you get started with Actions

name: GetExternalData

# Controls when the workflow will run
on:
  schedule:
    - cron: '0/10 * * * *'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    name: Start get

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v1

      # Runs a single command using the runners shell
      - name: Start Node
        run: |
          npm install
          npm run getAPI
